name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Install frontend dependencies
        working-directory: ./DevPlaygroundFrontEnd
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./DevPlaygroundFrontEnd
        run: npx playwright install --with-deps

      - name: Build frontend
        working-directory: ./DevPlaygroundFrontEnd
        run: npm run build

      - name: Start backend server
        working-directory: ./DevPlaygroundBackEnd
        run: |
          chmod +x gradlew
          ./gradlew bootRun &
          sleep 30

      - name: Start frontend dev server
        working-directory: ./DevPlaygroundFrontEnd
        run: |
          npm run dev &
          sleep 10

      - name: Run Playwright tests
        working-directory: ./DevPlaygroundFrontEnd
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: DevPlaygroundFrontEnd/playwright-report/
          retention-days: 30
